In [1]:
import numpy as np

identity = np.identity(2)
identity

array([[1., 0.],
       [0., 1.]])

In [2]:
noise = np.random.normal(size=(2, 2))
noise

array([[0.80119571, 0.70460862],
       [1.63671027, 1.14114752]])

In [3]:
identity + noise

array([[1.80119571, 0.70460862],
       [1.63671027, 2.14114752]])

In [ ]:
zeroes = np.zeros((2, 2))
zeroes